import type { ComponentProps } from "react";
import type { Ionicons } from "@expo/vector-icons";

type IconName = ComponentProps<typeof Ionicons>["name"];

export type FeatureStatus = "live" | "demo";
export type Phase = "P0" | "P1" | "P2";

export interface Feature {
  id: string;
  slug: string;
  name: string;
  icon: IconName;
  phase: Phase;
  pillar: string;
  star?: boolean;
  status: FeatureStatus;
  tagline: string;
  what: string;
  how: string[];
  beats: string;
  engineDemo?: boolean;
  demoLines?: string[];
}

export const PILLARS = [
  "Detect & Decide",
  "Calls & Voice",
  "Family & Seniors",
  "Money & Business",
  "Privacy & Exposure",
  "When It Goes Wrong",
  "Community & Intel",
] as const;

export const FEATURES: Feature[] = [
  { id: "T1", slug: "trust-engine", name: "Trust Engine & Score", icon: "git-network", phase: "P0", pillar: "Detect & Decide", star: true, status: "live", tagline: "One 1–100 score behind every surface.", what: "The brain. Every check returns one Trust Score with the top three reasons, localized — the product's vocabulary and the SDK's API contract.", how: ["Five signal families fused by a transparent combiner", "Multi-signal corroboration; calibrated uncertainty", "Full decision logging for the public calibration report"], beats: "McAfee's “96%” and the industry's accuracy theatre — by publishing calibration with receipts." },
  { id: "A1", slug: "ask-kinshield", name: "Ask KinShield", icon: "chatbubble-ellipses", phase: "P0", pillar: "Detect & Decide", star: true, status: "live", tagline: "Paste anything → verdict in seconds.", what: "The universal verdict box: paste, forward or dictate anything and get a Trust Score, the top reasons, and a recommended action in your language.", how: ["Multimodal pipeline → Trust Engine → localized actions", "Proactive: offers a check when a shield sees something odd", "Conversation memory per thread"], beats: "Norton Genie and Bitdefender Scamio — made proactive, multilingual, Canadian, and wired to actions.", engineDemo: true },
  { id: "S2", slug: "sms-shield", name: "SMS / RCS Shield", icon: "chatbox-ellipses", phase: "P0", pillar: "Detect & Decide", status: "live", tagline: "Scam texts filtered before the inbox.", what: "The wedge. Smishing is the highest-volume scam channel in Canada and the one the OS fully permits a third party to defend.", how: ["On-device multilingual classifier", "URL extraction into the Link Checker", "One-tap report into the community network"], beats: "Google/Apple filtering — beaten on Canadian patterns, twelve languages, and the report-to-protect-everyone loop." },
  { id: "L1", slug: "link-qr-checker", name: "Link & QR Checker", icon: "qr-code", phase: "P0", pillar: "Detect & Decide", status: "live", tagline: "Paste or scan; verdict in two seconds.", what: "Lookalike domains, homoglyphs, risky TLDs and brand-off-domain phishing caught before you tap — tuned for CRA, Interac, Canada Post.", how: ["Domain + certificate + homoglyph forensics", "Canadian brand whitelist", "Confidence-scored verdicts"], beats: "Norton Safe Web / McAfee WebAdvisor — plus Canadian tuning and QR-native UX.", engineDemo: true },
  { id: "V1", slug: "verifyca", name: "VerifyCA", icon: "business", phase: "P1", pillar: "Detect & Decide", star: true, status: "demo", tagline: "Check offers against Canadian registries.", what: "Investments checked against the CSA registration search and provincial regulators; job offers against corporate registries.", how: ["Registry layer with freshness monitoring", "Entity resolution across registries", "Newcomer-language explanations"], beats: "Nobody — no global product integrates thirteen Canadian provincial regulators.", demoLines: ["“Maple Yield Capital” → ⛔ NOT registered", "Source: CSA National Registration Search", "Matches a known fraud-alert pattern", "Unregistered investment offers are a major red flag"] },
  { id: "M2", slug: "multilingual", name: "Multilingual Defense", icon: "language", phase: "P0", pillar: "Detect & Decide", star: true, status: "live", tagline: "Twelve languages where losses concentrate.", what: "Detection, explanations, personas and Senior-Mode voice across the twelve languages where Canadian losses concentrate.", how: ["Multilingual ASR + per-language scam corpora", "Settlement-agency validation partners", "Human QA gates before a language ships"], beats: "Every competitor — all are English-first. This is where the market is undefended." },
  { id: "Z1", slug: "zero-day", name: "Zero-Day Anomaly", icon: "pulse", phase: "P1", pillar: "Detect & Decide", status: "demo", tagline: "The net under the nets.", what: "Per-user baselines flag events abnormal for this user, so a brand-new scam still trips an alarm by being out of pattern.", how: ["Per-user isolation-forest baselines", "Anomaly score feeds the Trust Engine", "Weekly self-supervised recalibration"], beats: "Pattern-matching incumbents' structural blind spot.", demoLines: ["Baseline: usually < $400, daytime, 6 saved payees", "⚠ New: $4,200 to an unsaved payee at 11:47pm", "Anomaly score 0.71 → folded into Trust Score", "Flagged even with no known script"] },

  { id: "C1", slug: "call-line", name: "The KinShield Line", icon: "call", phase: "P1", pillar: "Calls & Voice", star: true, status: "demo", tagline: "An AI receptionist that judges, not just answers.", what: "Unknown callers are screened by a selectable AI persona that runs script + synthesis analysis, then patches through, warns, or blocks — per family policy. Works on every handset.", how: ["Cloud voice layer → ASR → Trust Engine → policy engine", "Warm-transfer with whisper announcement", "Dual-provider failover; minute budgets"], beats: "Apple/Google screening (judgment vs reception), Hiya (consumer-owned), Robokiller.", demoLines: ["📞 Incoming: +1 604-555-0147 (unknown)", "Receptionist: “Who's calling and regarding what?”", "Script match: CRA-arrest · synthesis 0.7", "⛔ Blocked before your phone rang"] },
  { id: "C2", slug: "caller-intelligence", name: "Caller Intelligence", icon: "person-circle", phase: "P0", pillar: "Calls & Voice", status: "live", tagline: "Before the phone even rings.", what: "Live caller-ID labels, silences or blocks flagged numbers using the network plane — with private lookups and STIR/SHAKEN badges.", how: ["Sanctioned OS extension APIs", "Bloom-filter cache + private lookup", "Attestation surfaced as a visible badge"], beats: "Truecaller's core value, through privacy-preserving channels with consent-clean data.", demoLines: ["+1 604-555-0147 → ⛔ Likely scam (22 reports)", "Attestation: ❌ failed — likely spoofed", "Silenced before ring", "+1 416-555-0199 → ✅ Verified by carrier"] },
  { id: "A2", slug: "assist-mode", name: "Assist Mode", icon: "headset", phase: "P0", pillar: "Calls & Voice", star: true, status: "live", tagline: "Live, on-device coaching during a call.", what: "Put a call on speaker and tap Assist; the app analyses the audio entirely on-device and coaches in real time.", how: ["On-device transcription → script classifier", "Spoken prompts for Senior Mode", "Zero network dependency (one-party consent lawful)"], beats: "Google's mid-call alerts — beaten on languages, every handset, and what happens after." },
  { id: "V2", slug: "voice-lock", name: "Voice Lock", icon: "mic", phase: "P1", pillar: "Calls & Voice", status: "demo", tagline: "Family voiceprints, where the OS allows.", what: "Verifies a request against an enrolled, encrypted voice embedding — never raw audio; quarterly re-enrollment; CAI declaration before Quebec.", how: ["On-device speaker embeddings", "Liveness challenge + anti-replay", "Senior-friendly enrollment"], beats: "Pindrop's voice auth — at consumer price, with biometric compliance built in.", demoLines: ["Voiceprint: enrolled & encrypted ✓", "Request from “Mom” → verifying…", "Match 0.41 → ⛔ does not match enrolled voice", "Treat with extreme caution"] },
  { id: "H1", slug: "honeypot", name: "Honeypot Decoy Line", icon: "bug", phase: "P2", pillar: "Calls & Voice", star: true, status: "demo", tagline: "The app that fights back.", what: "Multiply-reported numbers get engaged by a decoy AI persona — wasting scammer hours and harvesting scripts into the network plane. Never uses your voice.", how: ["Decoy lines + persona library", "Forensic recording on our own consent footing", "Harvested intel improves detection — the legal flywheel"], beats: "Robokiller's answer-bots, modernized — a brand story no incumbent's legal team will approve.", demoLines: ["Decoy “Margaret” engaged the scammer", "Harvested: callback 604-555-0147", "Harvested: drop email recovery-cra@gmail.com", "6m 12s of scammer time wasted"] },

  { id: "F1", slug: "family-circle", name: "Family Circle", icon: "people", phase: "P0", pillar: "Family & Seniors", star: true, status: "live", tagline: "The household is the unit of protection.", what: "Paired accounts: adult children see flagged events, set policies, and get alerts across provinces and platforms. Up to 12 members; the senior never manages a password.", how: ["Household graph + role/permission model", "Policy engine consumed by every shield", "Audited approval log on the personal plane"], beats: "Every competitor — none has a multi-generational protection graph." },
  { id: "SM", slug: "senior-mode", name: "Senior Mode", icon: "accessibility", phase: "P0", pillar: "Family & Seniors", star: true, status: "live", tagline: "Big, calm, voice-first.", what: "A complete alternate presentation layer every feature renders into: large type, simple actions, verdicts spoken aloud, in twelve languages.", how: ["Simplified home: Help · Family · Check Call · Check Message", "Spoken verdicts via the device speech engine", "Co-designed with a seniors' organization"], beats: "Every competitor's one-size UI. Accessibility as a wedge." },
  { id: "S1", slug: "scam-drill", name: "Scam Drill", icon: "school", phase: "P1", pillar: "Family & Seniors", star: true, status: "live", tagline: "Inoculation, built for families.", what: "Opt-in simulations: a realistic (revealed-after) scam; whoever spots it gets the points. Builds the reflex no banner can.", how: ["Template library mirroring the live corpus", "Reveal-and-teach screens", "Household scoreboard; strict ethics rails"], beats: "Nobody — consumer scam inoculation doesn't exist. Cheap, sticky, viral." },
  { id: "B1", slug: "briefing", name: "Briefing & Heat Map", icon: "map", phase: "P1", pillar: "Family & Seniors", status: "live", tagline: "Where threats are surging, near you.", what: "A weekly localized briefing and a live community heat map of Canada.", how: ["Aggregation over the network plane (city-level, k-anonymity)", "Templated multilingual briefs", "Shareable cards that double as marketing"], beats: "Truecaller's community data — with consent-clean sourcing and Canadian locality." },

  { id: "C3", slug: "check-before-you-send", name: "Check Before You Send", icon: "card", phase: "P1", pillar: "Money & Business", star: true, status: "live", tagline: "The 10-second habit before money moves.", what: "Run the recipient and the three pressure questions — the consumer half of e-Transfer defence.", how: ["Recipient lookup across reports + crypto-intel", "Three pressure questions → verdict", "Optional family ping for large amounts"], beats: "Nobody — no consumer product checks an Interac recipient today.", engineDemo: true },
  { id: "W1", slug: "wire-guard", name: "Wire Guard (SMB)", icon: "swap-horizontal", phase: "P2", pillar: "Money & Business", star: true, status: "demo", tagline: "The Arup-killer for small business.", what: "Payment changes above a threshold require out-of-band release: a live selfie + spoken codeword + voice match. The deepfake can be perfect; it can't pass the channel it doesn't control.", how: ["Multi-factor release ceremony", "Policy engine per org → webhooks", "Signed, audited approval log"], beats: "Pindrop and every detector — procedure beats detection when detection can be fooled.", demoLines: ["Wire $48,000 to a NEW payee on a video call", "→ Out-of-band release required", "Live selfie ✓ · codeword ✓ · voice match ✓", "Released & audited — or BLOCKED if any factor fails"] },
  { id: "M1", slug: "meeting-assist", name: "Meeting Assist", icon: "videocam", phase: "P2", pillar: "Money & Business", star: true, status: "demo", tagline: "A second opinion on high-stakes video calls.", what: "With consent it flags visual-artifact anomalies and the guardrail that stops the attack: new payee + urgency → out-of-band Wire Guard required.", how: ["Sanctioned screen-capture with visible consent", "Frame sampling → detection ensemble", "Advisory flags, never verdicts"], beats: "Pindrop's meeting product — at SMB price, cross-platform, honest about limits.", demoLines: ["🎥 Live meeting · capture consent ON", "⚠ Lip-sync inconsistency 0.62 (advisory)", "🛑 New payee + urgency detected", "→ Out-of-band Wire Guard verification required"] },
  { id: "K1", slug: "sdk", name: "KinShield SDK", icon: "code-slash", phase: "P1", pillar: "Money & Business", star: true, status: "demo", tagline: "The same brain, licensed — the Bill C-15 product.", what: "Trust Engine API, a Bill C-15 control kit, the threat-intel feed with Canadian residency, and an FCAC reporting pipeline.", how: ["REST/GraphQL gateway + tenant isolation", "White-label control kit; per-check metering", "Compliance artifact pack (B-13, SOC 2, residency)"], beats: "Pindrop's enterprise position, attacked from below with consumer-proven detection.", demoLines: ["POST /v1/check → { trustScore: 7, verdict: dangerous }", "Bill C-15 cool-off + capability toggles", "Threat-intel feed · ca-central-1 residency", "$50K–$250K/yr + per-check"] },
  { id: "I2", slug: "insurance", name: "Insurance Benefit", icon: "umbrella", phase: "P2", pillar: "Money & Business", status: "demo", tagline: "Pre-evidenced claims, designed to be fast.", what: "A fraud-reimbursement benefit with a Canadian insurer; claims pre-evidenced by Incident Mode. Never “instant” or “no proof of loss”.", how: ["Underwriter/MGA partnership", "Claims API integrated with Incident Mode evidence", "Telemetry lowers premiums over time"], beats: "Aura's insurance — rebuilt for Canada with pre-evidenced claims.", demoLines: ["Family benefit: up to $10,000 CAD", "Claim #KS-4471 pre-filled from Incident Mode", "Status: under review · designed to be fast", "7 timestamped, hashed artifacts attached"] },

  { id: "Z2", slug: "zk-vault", name: "Zero-Knowledge Vault", icon: "lock-closed", phase: "P0", pillar: "Privacy & Exposure", star: true, status: "demo", tagline: "We hold ciphertext we cannot read.", what: "Voiceprints, transcripts, evidence and the family graph are encrypted on-device before storage. Even a subpoena yields nothing readable.", how: ["Client-side crypto + key derivation", "Shamir-style family recovery shares", "Enclave compute for rare server ops"], beats: "Every data-hungry incumbent — beaten by an architecture their business models forbid.", demoLines: ["🔒 Voiceprints · transcripts · evidence · graph", "Encrypted on-device before upload", "Server holds: ▒▒▒▒ ciphertext — unreadable", "Recovery: 3-of-5 family key shares"] },
  { id: "E2", slug: "exposure-sweep", name: "Exposure Sweep", icon: "scan", phase: "P1", pillar: "Privacy & Exposure", status: "demo", tagline: "What scammers know about you, shut down.", what: "Breach checks plus Canadian data-broker scans with statutory deletion demands under PIPEDA and Law 25 — not polite opt-outs.", how: ["Breach feeds + broker scrapers + legal templating", "Findings feed the Trust Engine", "Monthly re-sweep"], beats: "Incogni/DeleteMe (legal teeth + closed loop) and Cloaked.", demoLines: ["3 breaches found · 1 reused password", "→ Rotate it & add a passkey", "3 data brokers expose you", "Law 25 deletion demand filed ✓"] },
  { id: "P1", slug: "passkey-coach", name: "Passkey & Hardening Coach", icon: "key", phase: "P1", pillar: "Privacy & Exposure", status: "live", tagline: "Prevention's unglamorous half, gamified.", what: "A guided hardening program with a household score the Family Circle can see.", how: ["Curated playbooks per institution/carrier", "Deep links into settings flows", "Ties into Exposure Sweep findings"], beats: "Norton/McAfee's “security score” gimmicks — made actionable and family-visible." },

  { id: "I1", slug: "incident-mode", name: "Incident Mode", icon: "alert-circle", phase: "P0", pillar: "When It Goes Wrong", star: true, status: "live", tagline: "The panic button competitors forgot.", what: "A guided flow that compresses the catastrophic first hours: triage, evidence capture, pre-filled CAFC/police reports, scripted bank calls, and the recovery-scam warning.", how: ["Flow engine + institution playbook library", "Evidence vault → deep links + pre-filled forms", "Scheduled follow-ups; family alert"], beats: "Aura's restoration support — localized to Canadian institutions, triggered in seconds." },
  { id: "C5", slug: "crisis-vault", name: "Crisis Vault", icon: "medkit", phase: "P1", pillar: "When It Goes Wrong", star: true, status: "demo", tagline: "Sextortion: the four hours that decide everything.", what: "Evidence-based de-escalation, evidence preservation, StopNCII hash removal, guided reporting, and a silent trusted-contact alert.", how: ["Crisis flow → encrypted evidence (chain-of-custody)", "TakeItDown/StopNCII integrations", "Scripts vetted with mental-health partners"], beats: "Nobody addresses the first hours of sextortion. Parents buy Family tier for this alone.", demoLines: ["Breathe — they almost never leak. Do not pay.", "Evidence preserved (hashed, timestamped)", "StopNCII hash submitted ✓", "Silent trusted-contact alert sent"] },
  { id: "R1", slug: "recovery-line", name: "Recovery Line (human)", icon: "heart", phase: "P1", pillar: "When It Goes Wrong", star: true, status: "demo", tagline: "A trained human, in your language.", what: "A trauma-informed Canadian walks the family through the steps, joins three-way bank calls, and checks in weekly for three months.", how: ["Hiring/training pipeline; multilingual scripts", "Case management integrated with Incident Mode", "Agents see only what the user shares"], beats: "Aura/Norton's call centre — with languages, Canadian institutions, and a relationship.", demoLines: ["Advocate: Mei — EN/Cantonese/Mandarin", "Next 3-way with TD Fraud: today 4:30pm", "Case #KS-2231 · week 1 of 12", "You never repeat the story"] },
  { id: "L2", slug: "long-con-radar", name: "Long-Con Radar", icon: "time", phase: "P1", pillar: "When It Goes Wrong", star: true, status: "live", tagline: "For the scams that take weeks.", what: "Share a conversation as it evolves; KinShield tracks the script's progression and intervenes at the stage where intervention still works.", how: ["Per-thread encrypted conversation state", "Stage classification over message sequences", "Staged intervention co-designed with victim orgs"], beats: "Everyone — no product models scam progression over time." },

  { id: "C4", slug: "community-network", name: "Community Threat Network", icon: "globe", phase: "P0", pillar: "Community & Intel", status: "live", tagline: "One report protects everyone, in minutes.", what: "Numbers, senders, URLs and scripts flagged by one Canadian propagate to all — consented, pseudonymized, human-reviewed, aggregate to the CAFC.", how: ["Report flows → ingestion review queue", "Graph propagation → local caches", "Reputation decay; contributor karma"], beats: "Truecaller's network effect, rebuilt on consent." },
  { id: "E1", slug: "email-guard", name: "Email Guard", icon: "mail", phase: "P1", pillar: "Community & Intel", status: "demo", tagline: "Phishing scanning for the inbox.", what: "A read-only, revocable OAuth connection scans for impersonation, lookalike senders and malicious links — verdicts explained, not just spam-foldered.", how: ["OAuth + SPF/DKIM/DMARC forensics + content model", "Link Checker on every URL", "Bodies never retained post-verdict"], beats: "McAfee/Norton email scanning — plus Canadian context and twelve languages.", demoLines: ["no-reply@cra-refund-gov.xyz → ⛔ 7/100", "security@rbc-secure-alert.top → ⛔ 9/100", "team@figma.com → ✅ 96/100", "2 flagged · bodies discarded after scan"] },
];

export const FEATURES_BY_SLUG: Record<string, Feature> = Object.fromEntries(FEATURES.map((f) => [f.slug, f]));
export const liveCount = FEATURES.filter((f) => f.status === "live").length;
